[package]
name = "is_ape_owner"
type = "bin"
authors = [""]
compiler_version = ">=0.30.0"

[dependencies]
ethereum = { path = "../../../../ethereum/circuits/lib" }
token = { path = "../../../ethereum/circuits/lib" }
